spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 
    username: 
    password: 

server:
    port: 8080
    
app:
   jwt:
      secret: javatech
      TokenExpiry: 36000000
      
